[package]
name = "bootstrap"
version = "0.1.0"
edition = "2021"
links = "c"
build = "build.rs"

[dependencies]
aws_lambda_libc = { path = "../rust-binding" }
libc = { version = "0.2.167", default-features = false }

[profile.release]
panic = "abort"
lto = true
