[package]
name = "zort-rust-binding"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = { version = "0.2.167", default-features = false }

[build-dependencies]
cc = "1.0"

[lib]
name = "zort_rust_binding"
path = "src/lib.rs"

[profile.release]
panic = "abort"
lto = true
